config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'chat#dashboard'

  post 'messages', to: 'messages#create'
  post 'messages/like/:id', to: 'messages#like'
  post 'messages/unlike/:id', to: 'messages#unlike'
  get 'users/profile/:email', to: 'users#profile', as: :profile
  post 'users/block/:id', to: 'users#block_user', as: :block_user
  post 'users/unblock/:id', to: 'users#unblock_user', as: :unblock_user
  post 'users/avatar', to: 'users#change_avatar', as: :change_avatar
  get '/uploads/user/avatar/:id/:filename' => 'gridfs#avatar'
  get '/users/top_users', to: 'users#top_users', as: :top_users
  get '/messages/get_old_messages', to: 'chat#get_old_messages'
end

app/models/message.rb
class Message
  include Mongoid::Document

  belongs_to :user, inverse_of: :messages
  field :text
  field :posted_on, type: Time
  has_and_belongs_to_many :likes, class_name: 'User', inverse_of: :liked_messages
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time

  has_many :messages, inverse_of: :user
  has_and_belongs_to_many :liked_messages, class_name: 'Message', inverse_of: :likes

  has_and_belongs_to_many :blocked_users, class_name: 'User', inverse_of: :blocked_by
  has_and_belongs_to_many :blocked_by, class_name: 'User', inverse_of: :blocked_users

  attr_accessor :avatar
  mount_uploader :avatar, AvatarUploader

  def likes
    messages.reduce(0) {|sum, message| sum + message.likes.size }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/chat_controller.rb
class ChatController < ApplicationController
  before_action :authenticate_user!

  def dashboard
    currently_blocked = current_user.blocked_users.map(&:id)
    @chat_messages = Message.where(:user.nin => currently_blocked)
                            .order_by(posted_on: 'desc')
                            .take(20).reverse
  end

  def get_old_messages
    currently_blocked = current_user.blocked_users.map(&:id)
    @chat_messages = Message.where(:user.nin => currently_blocked)
                            .order_by(posted_on: 'desc')[params[:start].to_i, 20].reverse
    render :layout => false
  end
end

app/controllers/gridfs_controller.rb
class GridfsController < ApplicationController
  def avatar
    @user = User.find params[:id]
    content = @user.avatar.read
    send_data content, type: @user.avatar.file.content_type, disposition: "inline"
    expires_in 0, public: true
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!

  def create
    message = Message.new
    message.user = current_user
    message.posted_on = Time.new
    message.text = params[:text]
    message.save
    render nothing: true, status: 201
  end

  def like
    message = Message.find(params[:id])
    message.likes << current_user
    message.save
    render nothing: true, status: 200
  end

  def unlike
    message = Message.find(params[:id])
    message.likes.delete current_user
    message.save
    render nothing: true, status: 200
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def block_user
    blocked = User.find(params[:id])
    current_user.blocked_users.push blocked
    current_user.save
    render nothing: true, status: 200
  end

  def unblock_user
    blocked = User.find(params[:id])
    current_user.blocked_users.delete blocked
    current_user.save
    render nothing: true, status: 200
  end

  def profile
    @user = User.find_by(email: params[:email] + '.' + params[:format])
  end

  def change_avatar
    current_user.avatar = params[:user][:avatar]
    current_user.save
    redirect_to :back
  end

  def top_users
    @top_users = User.all.map do |u|
      blocks = u.blocked_by.size**2
      blocks = 1 if blocks == 0
      {user: u, rating: u.likes / blocks.to_f}
    end.sort_by {|user| user[:rating] }.reverse
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chat/_message.html.erb
<div id="<%= message.id %>">
  <hr>
  <% if message.user.avatar? %>
    <%= link_to image_tag(src: message.user.avatar, title: message.user.email), profile_path(email: message.user.email) %>
  <% else %>
    <%= link_to image_tag("/User.png", class: "img-small", title: message.user.email), profile_path(email: message.user.email) %>
  <% end %>

  <%= message.text %>
  <div class="right"><%= message.posted_on %></div>

  <% if message.likes.include? current_user %>
    <button class="right unlike-btn" onclick="unlikeMessage('<%= message.id %>')"></button>
    <button class="right like-btn" onclick="likeMessage('<%= message.id %>')" style="display: none;"></button>
  <% else %>
    <button class="right like-btn" onclick="likeMessage('<%= message.id %>')"></button>
    <button class="right unlike-btn" onclick="unlikeMessage('<%= message.id %>')" style="display: none;"></button>
  <% end %>

  <div class="right">
    Likes: <span class="number-of-likes"><%= message.likes.size.to_i %></span>
  </div>
</div>

app/views/chat/dashboard.html.erb
<div id="chat">
  <button id="see-more" onclick="getOldMessages()">See more</button>
  <%= render partial: "message", collection: @chat_messages %>
</div>

<hr>
<textarea id="new-message" name="text"></textarea>
<button id="submit-new-message" onclick="submitMessage($('#new-message').val())">
  Submit
</button>

app/views/chat/get_old_messages.html.erb
<%= render partial: "message", collection: @chat_messages %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Newsfeed</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller_name %> <%= action_name %>">
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<% if current_user != nil %>
  <nav>
    <%= link_to('Chat', root_url) %>
    <%= link_to('Profile', profile_path(email: current_user.email)) %>
    <%= link_to('Rankings', top_users_path) %>
    <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
    <b class="left"><%= current_user.email %></b> 
  </nav> 
  <hr>
<% end %>
<%= yield %>

</body>
</html>

app/views/users/profile.html.erb
<h1>User: <%= @user.email %></h1>

<% if @user.avatar? %>
  <%= image_tag src=@user.avatar %>
<% else %>
  <%= image_tag("/User.png") %>
<% end %>

<%= form_tag(change_avatar_path, :html => { :multipart => true }) do %>
  <%= file_field :user, :avatar %>

  <div class="actions">
    <%= submit_tag("Upload") %>
  </div>
<% end %>

<hr>
<% if @user != current_user %>
  <% if current_user.blocked_users.include? @user %>
    <button id="unblock-btn" onclick="unblockUser('<%= @user.id %>')">Unblock</button>
    <button id="block-btn" onclick="blockUser('<%= @user.id %>')" style="display: none;">
      Block
    </button>
  <% else %>
    <button id="block-btn" onclick="blockUser('<%= @user.id %>')">Block</button>
    <button id="unblock-btn" onclick="unblockUser('<%= @user.id %>')" style="display: none;">
      Unblock
    </button>
  <% end %>
<% end %>

app/views/users/top_users.html.erb
<table>
  <thead>
    <th>User</th>
    <th>Rating</th>
  </thead>
  <tbody>
  <% @top_users.each do |user| %>
    <tr>
      <td><%= user[:user].email %></td>
      <td><%= user[:rating] %></td>
    </tr>
  <% end %>
  </tbody>